/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

/**
 *
 * @author lucia
 */
public class ConfigPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfigPanel
     */
    public ConfigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jComboDifficulty = new javax.swing.JComboBox<>();
        jButtonStart = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SNAKE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabelLevel.setText("Level");
        add(jLabelLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jComboDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Difficult" }));
        add(jComboDifficulty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(this::jButtonStartActionPerformed);
        add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        int speed;

        switch (jComboDifficulty.getSelectedIndex()) {
            case 0:
                speed = 300;
                break; // Easy
            case 1:
                speed = 150;
                break; // Medium
            default:
                speed = 80;
                break; // Difficult
        }
        Game game = (Game) javax.swing.SwingUtilities.getWindowAncestor(this);
        game.startGame(speed);

    }//GEN-LAST:event_jButtonStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JComboBox<String> jComboDifficulty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLevel;
    // End of variables declaration//GEN-END:variables
}
