/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

import com.mycompany.snake.interfaces.Incrementer;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author luctroort
 */
public class ScoreBoard extends javax.swing.JPanel implements Incrementer {

    private int score;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        score = 0;
        incrementScore(0);
    }

    public void incrementScore(int increment) {
        score += increment;
        jLabel1.setText("Score: " + score);
    }

    public int getHighScore() {
        try (BufferedReader br = new BufferedReader(new FileReader("highscore.txt"))) {
            return Integer.parseInt(br.readLine());
        } catch (IOException | NumberFormatException e) {
            return 0;
        }
    }

    public void saveHighScore() {
        int currentHighScore = getHighScore();
        if (score > currentHighScore) {
            try (PrintWriter out = new PrintWriter(new FileWriter("highscore.txt"))) {
                out.println(score);
            } catch (IOException e) {
                System.err.println("Error guardando record: " + e.getMessage());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void reset() {
        score = 0;
        incrementScore(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
